### ISSUE TITLE
Make logs more human-readable

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/ontology-toolkit#52]
I'd like to see log statements like:

INFO: Generating legacy RDFS annotations
INFO:  Transform {'action': 'transform', 'tool': 'serializer', 'source': '{output}/rdfsAnnotations.ttl', 'target': '{output}/rdfsAnnotations.ttl'}
_[leave blank space between entries]_
INFO: Copying license to output directory.
INFO: Copy {'action': 'copy', 'source': '{input}/LICENSE.txt', 'target': '{output}'}

**Comment by sa-bpelakh** [comment]
So, if I added a `message` field to actions as follows:
```yaml
- action: "transform"
  message: "Serializing ontology as RDF/XML"
  tool: "xml-serializer"
  source: "{output}"
  target: "{output}"
  rename:
    from: "(.*)\\.ttl"
    to: "\\g<1>.rdf"
  includes:
    - "*.ttl"
```
And have that message emitted as `INFO` when the action is started (prefixed with an empty line), would that satisfy your requirement? The message string would be subject to variable substitution, so you could use it as a template as well. The actual properties of the action, I feel, should still only be output at the DEBUG level, which you can make visible by using the `--debug` option.
